### ISSUE TITLE
Doesnt work in sourcetree

### ISSUE THREAD

**Issue by callerc1** [git-hooks/git-hooks#13]
This is because sourcetree doesn't know what the `git-hooks` command/executable is. Sourcetree seems to be building its own PATH.

**Comment by callerc1** [comment]
Would it be worth prepending absExePath to the template tplPostInstall ? eg 
```
#!/usr/bin/env bash
/usr/local/bin/git-hooks run "$0" "$@"
```

this way it will always work regardless of running in a git gui.

?

**Comment by callerc1** [comment]
... Also, perhaps a check to see if the executable exists in current location? if its been moved a message to say `Try running 'git-hooks install' again` or even a new `git-hooks update-exe` method which updates the path inside the templates. Perhaps the "command not found" message will be enough tho to make this obvious.

**Comment by CatTail** [comment]
There is no way to find absolute path of `git-hooks` if `PATH` variable is being modified.

**Comment by callerc1** [comment]
Does [this](https://github.com/git-hooks/git-hooks/blob/master/util.go#L166) method not do that? obviously if `PATH` is modified and `git-hooks` cant be found then all hooks will fail. This is where the message part of my comment could come in. A work around is to launch source tree from a shell where your `PATH` has been set correctly.

**Comment by CatTail** [comment]
I don't want to restrict the location of `git-hooks` in `/usr/local/bin/git-hooks`, any better idea?

**Comment by CatTail** [comment]
Close it for now.

**Comment by callerc1** [comment]
i'm sort of confused as to how it would be restricting it to that location? when dynamically building the path to git-hooks via the `absExePath` method.
