### ISSUE TITLE
Semver warning when trying to update

### ISSUE THREAD

**Issue by morganestes** [git-hooks/git-hooks#14]
I tried to update a brand-new install of 1.1.3 and it gave me a Semver warning/notice at the end. I'm not sure if that means something failed or if it's just a heads-up:

```console
$ git hooks update
Check latest version...
Current version is v1.1.3, latest version is 1.1.3
Semver parse error strconv.ParseUint: parsing "": invalid syntax
```

**Comment by CatTail** [comment]
Fixed. I release a malformed version number.
