### ISSUE TITLE
Homebrew formula?

### ISSUE THREAD

**Issue by jasonkarns** [git-hooks/git-hooks#34]
Would there be interest to replace the existing homebrew formula (which installs icefox's original), with this fork?

I definitely prefer using homebrew to manage installed software myself.

https://github.com/Homebrew/homebrew-core/blob/master/Formula/git-hooks.rb

**Comment by kfkonrad** [comment]
There's the formula [git-hooks-go](https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/git-hooks-go.rb) now. Can this issue be closed?
