### ISSUE TITLE
Getting Started wiki has typos

### ISSUE THREAD

**Issue by jasonkarns** [git-hooks/git-hooks#38]
The [Getting Started](https://github.com/git-hooks/git-hooks/wiki/Get-Started) wiki page (which doesn't appear editable by non-contributors) repeatedly references `git config --set --system hooks.global`. However `--set` is not a valid option to `git config`. I'm not sure where that came from (perhaps an old version of git?), but as of 2.29, `--set` is not a valid option. Perhaps that was a typo meant to be `--get`??

**Comment by CatTail** [comment]
Hi @jasonkarns, thanks for report this issue, at the time I write that Getting Started page `git config` do have `--set` option, it seems we can archive the same thing with `--add` option, I have updated the documentation to use `--add`. Also, feel free to edit the wiki page if there are other mistakes, I have configured it to be editable by non-contributors.

**Comment by jasonkarns** [comment]
> I have configured it to be editable by non-contributors.

Cool! I updated the wiki; `--add` is for config options that can have multiple values. Running that command multiple times will not overwrite an existing value but would instead insert multiple entries. I presume that git-hooks does not handle multiple entries for this config option; only one. So I've updated the docs to reflect that.
